### ISSUE TITLE
Doprava

### ISSUE THREAD

**Issue by dzejar** [mgp4/aws-hackathon-2015#3]
V kolik se sejdem? Jsme všichni schopní tam být třeba půl hodiny předem (**POZOR: zčátek je v 18:00**, kdysi se někde uvádělo 19:00) a ještě prodiskutovat ta témata?

Budu pravděpodobně vyjíždět někdy okolo 16:30 - 17:00 ze Závišic, kdyby se chtěl někdo přidat. Jinak víte někdo jak je to s parkováním v okolí hubu?

**Comment by dzejar** [comment]
Případně někdy mezi 13:00 a 14:00 bych chtěl vyjet z Brna.

**Comment by garncarz** [comment]
Hub má vlastní parkoviště, ale brána bývá zavřená, kdyžtak možná zastavíš u chodníku a skočíš dovnitř, jestli ti neotevřou. Ale @pholasek o tom myslím ví víc. A @ep69 nesleduje projekt. :see_no_evil: :smile:

**Comment by pholasek** [comment]
Jedem se @ep69 z Brna ve tři, takže doufám, že tam v pět budem. O parkování vím pouze toto: http://www.hubostrava.cz/parkovani/, ale počítám s tím, že nás tam nechají parkovat :sweat_smile:

**Comment by dzejar** [comment]
Všichni jsme v pořádku dorazili :+1:
