### ISSUE TITLE
Wozniak je gay

### ISSUE THREAD

**Issue by ep69** [mgp4/aws-hackathon-2015#4]
SSIA

**Comment by wozniakjan** [comment]
Emperor Palpatine se konecne zapojil do projektu! At se dari chlapi, priste bych se pridal, pokud teda nevadi, ze jsem gay..

**Comment by garncarz** [comment]
@wozniakjan Jsem tě přizval do projektu, Wozy, pokud se chceš zapojit. Říkali jsme si s JR, že bychom na tom pokračovali, ať to něco umí.

**Comment by dzejar** [comment]
:+1: Lajk, stejně jako Tři mušketýři byli 4, tak by tým MGP4 měl mít 5 členů, aby byl úplný.

**Comment by ep69** [comment]
Aby brzo nemel jen dva..
S.

Dne 14. prosince 2015 12:20 Jan Richter notifications@github.com
napsal(a):

**Comment by wozniakjan** [comment]
diky! akorat teda o django nevim nic a sycet jako krajta mi taky moc nejde, ale treba muzu kreslit aspon obrazky do dokumentace pro zacatek

**Comment by garncarz** [comment]
Super, ještě by tě mohl @ep69 přizvat do Slacku. Django je v klidu, když si zkusíš zprovoznit projekt podle README, tak by neměl být problém. ~~(Jo, jedině snad si vynutit `DummyCache`, musím to tam změnit, aby to nepožadovalo cache.)~~

**Comment by ep69** [comment]
Wozniak prizvan. Zaviram. (Kdyz uz mam commit, at mam i uzavrene issue.)

**Comment by garncarz** [comment]
Jen ten commit je pod emailem neregistrovaným v GitHubu, takže ti to nepočítá. :skull:

**Comment by ep69** [comment]
SHIT!!!
